/**
 * Expanded Russian + popular catalog for instant "drunk-proof" search
 * Covers mainstream RU hits that iTunes often misses by artist-only query
 */
window.MUSIC_CATALOG = [
  // Лепс
  { title: "Рюмка водки на столе", artist: "Григорий Лепс", tags: "лепс рюмка водки grigory leps" },
  { title: "Натали", artist: "Григорий Лепс", tags: "лепс натали" },
  { title: "Я поднимаю свой бокал", artist: "Григорий Лепс", tags: "лепс бокал" },
  { title: "Водопадом", artist: "Григорий Лепс", tags: "лепс водопадом" },
  { title: "Самый лучший день", artist: "Григорий Лепс", tags: "лепс лучший день" },
  { title: "Я тебя не люблю", artist: "Григорий Лепс", tags: "лепс" },
  { title: "Лондон", artist: "Григорий Лепс & Тимати", tags: "лепс тимати лондон" },
  // Morgenstern / Элджей
  { title: "Cadillac", artist: "MORGENSHTERN & Элджей", tags: "моргенштерн morgenshtern элджей" },
  { title: "Новая волна", artist: "MORGENSHTERN", tags: "моргенштерн morgenshtern" },
  { title: "ДОМ", artist: "MORGENSHTERN", tags: "моргенштерн дом" },
  { title: "КРАСНЫЙ ФЛАГ", artist: "MORGENSHTERN", tags: "моргенштерн" },
  { title: "ICE", artist: "MORGENSHTERN", tags: "моргенштерн" },
  { title: "Yung Kaef", artist: "Элджей", tags: "элджей allj" },
  { title: "Розовое вино", artist: "Элджей & Feduk", tags: "элджей feduk вино" },
  { title: "Минимал", artist: "Элджей", tags: "элджей" },
  // Instasamka
  { title: "Money Rain", artist: "INSTASAMKA", tags: "инстасамка instasamka" },
  { title: "За деньги да", artist: "INSTASAMKA", tags: "инстасамка" },
  { title: "Lipsi Ha", artist: "INSTASAMKA", tags: "инстасамка lipsi" },
  { title: "Отключаю телефон", artist: "INSTASAMKA", tags: "инстасамка" },
  { title: "BBQ", artist: "INSTASAMKA", tags: "инстасамка" },
  // Jony
  { title: "Комета", artist: "JONY", tags: "джони jony" },
  { title: "Аллея", artist: "JONY", tags: "джони jony" },
  { title: "Титры", artist: "JONY", tags: "джони" },
  { title: "Лали", artist: "JONY", tags: "джони lali" },
  { title: "Камин", artist: "JONY & Andro", tags: "джони andro" },
  // Artik Asti / Anna Asti
  { title: "Истеричка", artist: "Artik & Asti", tags: "артист асти artik" },
  { title: "Грустный дэнс", artist: "Artik & Asti", tags: "артист асти" },
  { title: "Под гипнозом", artist: "Artik & Asti", tags: "артист асти" },
  { title: "Девочка танцуй", artist: "Artik & Asti", tags: "артист асти" },
  { title: "Царица", artist: "ANNA ASTI", tags: "анна асти anna" },
  { title: "По барам", artist: "ANNA ASTI", tags: "анна асти" },
  { title: "Сияй", artist: "ANNA ASTI", tags: "анна асти" },
  // Miyagi
  { title: "I Got Love", artist: "Miyagi & Эндшпиль", tags: "мияги miyagi эндшпиль" },
  { title: "Тамада", artist: "Miyagi & Andy Panda", tags: "мияги" },
  { title: "Fire Man", artist: "Miyagi & Эндшпиль", tags: "мияги" },
  { title: "Captain", artist: "Miyagi & Эндшпиль", tags: "мияги" },
  { title: "Самурай", artist: "Miyagi & Эндшпиль", tags: "мияги" },
  // Скриптонит
  { title: "Положение", artist: "Скриптонит", tags: "скриптонит scriptonite" },
  { title: "Цепи", artist: "Скриптонит", tags: "скриптонит" },
  { title: "Животные", artist: "Скриптонит", tags: "скриптонит" },
  { title: "Ламбада", artist: "T-Fest & Скриптонит", tags: "скриптонит t-fest" },
  { title: "Мультибрендовый", artist: "Скриптонит", tags: "скриптонит" },
  // Zivert / Niletto / HammAli
  { title: "Life", artist: "Zivert", tags: "зиверт zivert" },
  { title: "Credo", artist: "Zivert", tags: "зиверт" },
  { title: "ЯТЛ", artist: "Zivert", tags: "зиверт ятл" },
  { title: "Beverly Hills", artist: "Zivert", tags: "зиверт" },
  { title: "Любимка", artist: "NILETTO", tags: "нилетто niletto" },
  { title: "Краш", artist: "NILETTO", tags: "нилетто" },
  { title: "Птичка", artist: "HammAli & Navai", tags: "hammali navai хаммали" },
  { title: "Пустите меня на танцпол", artist: "HammAli & Navai", tags: "hammali танцпол" },
  { title: "Девочка-война", artist: "HammAli & Navai", tags: "hammali" },
  // Крид / MACAN / Мот
  { title: "Грехи", artist: "Егор Крид", tags: "крид egor creed" },
  { title: "Сердцеедка", artist: "Егор Крид", tags: "крид" },
  { title: "Холостяк", artist: "Егор Крид", tags: "крид" },
  { title: "Минор", artist: "MACAN", tags: "макан macan" },
  { title: "ASPHALT 8", artist: "MACAN", tags: "макан" },
  { title: "Кино", artist: "MACAN & SCIRENA", tags: "макан" },
  { title: "Пьяным", artist: "Мот", tags: "мот mot" },
  { title: "Когда исчезнет слово", artist: "Мот", tags: "мот" },
  // Классика / рок
  { title: "Группа крови", artist: "Кино", tags: "кино цой группа крови" },
  { title: "Звезда по имени Солнце", artist: "Кино", tags: "кино цой" },
  { title: "Пачка сигарет", artist: "Кино", tags: "кино цой" },
  { title: "Кукушка", artist: "Кино", tags: "кино цой" },
  { title: "Выхода нет", artist: "Сплин", tags: "сплин" },
  { title: "Романс", artist: "Сплин", tags: "сплин" },
  { title: "Владивосток 2000", artist: "Мумий Тролль", tags: "мумий тролль" },
  { title: "Невеста", artist: "Мумий Тролль", tags: "мумий" },
  { title: "Это всё", artist: "ДДТ", tags: "ддт шевчук" },
  { title: "Что такое осень", artist: "ДДТ", tags: "ддт осень" },
  { title: "Тучи", artist: "Иванушки International", tags: "иванушки тучи" },
  { title: "Тополиный пух", artist: "Иванушки International", tags: "иванушки" },
  { title: "Аривидерчи", artist: "Руки Вверх", tags: "руки вверх" },
  { title: "Крошка моя", artist: "Руки Вверх", tags: "руки вверх" },
  { title: "18 мне уже", artist: "Руки Вверх", tags: "руки вверх" },
  // Баста / рэп
  { title: "Сансара", artist: "Баста", tags: "баста bastа sansara" },
  { title: "Моя игра", artist: "Баста", tags: "баста" },
  { title: "Вызов", artist: "Баста", tags: "баста" },
  { title: "Улица Русская", artist: "Каста", tags: "каста" },
  { title: "Вокруг шум", artist: "Каста", tags: "каста" },
  // Pop
  { title: "Молодость", artist: "Dabro", tags: "дабро dabro" },
  { title: "Юность", artist: "Dabro", tags: "дабро" },
  { title: "На часах ноль-ноль", artist: "Dabro", tags: "дабро" },
  { title: "Улети", artist: "Rauf & Faik", tags: "рауф файк rauf" },
  { title: "Детство", artist: "Rauf & Faik", tags: "рауф файк" },
  { title: "Я в моменте", artist: "Джарахов & Markul", tags: "джарахов markul" },
  { title: "Без тебя я не я", artist: "Ramil'", tags: "рамиль ramil" },
  { title: "Синяя вечность", artist: "Баста & Смоки Мо", tags: "баста смоки" },
  { title: "Цвет настроения синий", artist: "Филипп Киркоров", tags: "киркоров синий" },
  { title: "Жар-птица", artist: "Дима Билан", tags: "билан" },
  { title: "Невозможное возможно", artist: "Дима Билан", tags: "билан" },
  { title: "Пули", artist: "Егор Крид & GUF", tags: "крид гуф" },
  { title: "Качели", artist: "Мот", tags: "мот" },
  { title: "По краю", artist: "Макс Корж", tags: "корж" },
  { title: "Малый повзрослел", artist: "Макс Корж", tags: "корж" },
  { title: "Оптимист", artist: "Макс Корж", tags: "корж" },
  { title: "Горы по колено", artist: "Макс Корж", tags: "корж" },
  { title: "2 типа людей", artist: "Макс Корж", tags: "корж" },
  // Шансон / застольные
  { title: "Владимирский централ", artist: "Михаил Круг", tags: "круг шансон централ" },
  { title: "Жиган-лимон", artist: "Михаил Круг", tags: "круг" },
  { title: "Магадан", artist: "Михаил Круг", tags: "круг магадан" },
  { title: "Букет", artist: "Александр Розенбаум", tags: "розенбаум" },
  { title: "Гоп-стоп", artist: "Александр Розенбаум", tags: "розенбаум гоп" },
  // International party
  { title: "Blinding Lights", artist: "The Weeknd", tags: "уикенд weeknd" },
  { title: "Shape of You", artist: "Ed Sheeran", tags: "ed sheeran" },
  { title: "Believer", artist: "Imagine Dragons", tags: "imagine dragons" },
  { title: "Thunder", artist: "Imagine Dragons", tags: "imagine dragons" },
  { title: "Bohemian Rhapsody", artist: "Queen", tags: "queen богемская" },
  { title: "Don't Stop Me Now", artist: "Queen", tags: "queen" },
  { title: "Uptown Funk", artist: "Bruno Mars", tags: "bruno mars" },
  { title: "As It Was", artist: "Harry Styles", tags: "harry styles" },
  { title: "Flowers", artist: "Miley Cyrus", tags: "miley" },
  { title: "Levitating", artist: "Dua Lipa", tags: "dua lipa" },
  { title: "One Dance", artist: "Drake", tags: "drake" },
  { title: "Starboy", artist: "The Weeknd", tags: "weeknd" },
  { title: "HUMBLE.", artist: "Kendrick Lamar", tags: "kendrick" },
  { title: "In The End", artist: "Linkin Park", tags: "linkin park" },
  { title: "Numb", artist: "Linkin Park", tags: "linkin park" },
  { title: "Smells Like Teen Spirit", artist: "Nirvana", tags: "nirvana" },
  { title: "Wonderwall", artist: "Oasis", tags: "oasis" },
  { title: "Mr. Brightside", artist: "The Killers", tags: "killers" },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", tags: "guns" },
  { title: "September", artist: "Earth, Wind & Fire", tags: "september" },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", tags: "whitney" },
  { title: "Billie Jean", artist: "Michael Jackson", tags: "jackson" },
  { title: "Despacito", artist: "Luis Fonsi", tags: "despacito" },
  { title: "Gangnam Style", artist: "PSY", tags: "psy" },
  // More RU
  { title: "Никаких больше вечеринок", artist: "Долгая Счастливая Жизнь", tags: "вечеринок" },
  { title: "Экспонат", artist: "Ленинград", tags: "ленинград шнур экспонат" },
  { title: "В Питере пить", artist: "Ленинград", tags: "ленинград питер" },
  { title: "WWW", artist: "Ленинград", tags: "ленинград" },
  { title: "Рыба", artist: "Ленинград", tags: "ленинград" },
  { title: "Вояж", artist: "Ленинград", tags: "ленинград вояж" },
  { title: "Терминатор", artist: "Пошлая Молли", tags: "пошлая молли" },
  { title: "Любимая песня твоей сестры", artist: "Пошлая Молли", tags: "пошлая молли" },
  { title: "Минивен", artist: "Пошлая Молли", tags: "пошлая молли" },
  { title: "Асфальт", artist: "FACE", tags: "фейс face" },
  { title: "Юморист", artist: "FACE", tags: "фейс" },
  { title: "Последний вагон", artist: "Би-2", tags: "би-2 bi-2" },
  { title: "Полковнику никто не пишет", artist: "Би-2", tags: "би-2 полковник" },
  { title: "Серебро", artist: "Би-2", tags: "би-2" },
  { title: "Мой рок-н-ролл", artist: "Би-2 & Чичерина", tags: "би-2" },
  { title: "Я свободен", artist: "Кипелов", tags: "кипелов свободен" },
  { title: "Я хочу быть с тобой", artist: "Nautilus Pompilius", tags: "наутилус" },
  { title: "Крылья", artist: "Nautilus Pompilius", tags: "наутилус крылья" },
  { title: "Скованные одной цепью", artist: "Nautilus Pompilius", tags: "наутилус" },
  { title: "Шарманка", artist: "ДДТ", tags: "ддт" },
  { title: "Метель", artist: "ДДТ", tags: "ддт" },
  { title: "Земля", artist: "Игорь Николаев", tags: "николаев" },
  { title: "Выпьем за любовь", artist: "Игорь Николаев", tags: "николаев выпьем" },
  { title: "Миллион алых роз", artist: "Алла Пугачёва", tags: "пугачева розы" },
  { title: "Паромщик", artist: "Алла Пугачёва", tags: "пугачева" },
  { title: "Арлекино", artist: "Алла Пугачёва", tags: "пугачева" },
  { title: "Белый лебедь", artist: "Валерия", tags: "валерия" },
  { title: "Часики", artist: "Валерия", tags: "валерия" },
  { title: "Океан и три реки", artist: "Валерия & Стас Пьеха", tags: "валерия" },
  { title: "Город, которого нет", artist: "Игорь Бутман / из к/ф", tags: "город которого нет" },
  { title: "Подмосковные вечера", artist: "В. Трошин", tags: "подмосковные вечера" },
  { title: "Калинка", artist: "Русская народная", tags: "калинка" },
  { title: "Катюша", artist: "Русская народная", tags: "катюша" },
  { title: "Смуглянка", artist: "Русская народная", tags: "смуглянка" },
  { title: "Синий платочек", artist: "Русская народная", tags: "платочек" },
  { title: "Ой, мороз мороз", artist: "Русская народная", tags: "мороз" },
  { title: "Ты ж мене пидманула", artist: "Украинская народная", tags: "пидманула" },
  { title: "Любви море", artist: "Лолита", tags: "лолита" },
  { title: "Пошлой", artist: "Мот & Ани Лорак", tags: "мот лорак" },
  { title: "Королева", artist: "Мот", tags: "мот" },
  { title: "Мама, я танцую", artist: "Ханна", tags: "ханна" },
  { title: "Невеста", artist: "Любэ", tags: "любе" },
  { title: "Конь", artist: "Любэ", tags: "любе конь" },
  { title: "Комбат", artist: "Любэ", tags: "любе комбат" },
  { title: "Там, за туманами", artist: "Любэ", tags: "любе" },
  { title: "Давай за...", artist: "Любэ", tags: "любе давай" },
  { title: "Зеленоглазое такси", artist: "Михаил Боярский", tags: "боярский такси" },
  { title: "Всё, что касается", artist: "Город 312", tags: "город 312" },
  { title: "Останусь", artist: "Город 312", tags: "город 312" },
  { title: "Вне зоны доступа", artist: "Город 312", tags: "город 312" },
  { title: "Мой роман", artist: "Ёлка", tags: "елка ёлка" },
  { title: "На большом воздушном шаре", artist: "Ёлка", tags: "елка" },
  { title: "Прованс", artist: "Ёлка", tags: "елка прованс" },
  { title: "Грею счастье", artist: "Ёлка", tags: "елка" },
  { title: "Я не могу без тебя", artist: "Альянс", tags: "альянс на заре" },
  { title: "На заре", artist: "Альянс", tags: "альянс на заре" },
  { title: "Крылатые качели", artist: "из к/ф Приключения Электроника", tags: "электроник качели" },
  { title: "Прекрасное далёко", artist: "из к/ф Гостья из будущего", tags: "прекрасное далеко" },
  { title: "До свидания, Москва", artist: "из к/ф", tags: "до свидания москва" },
  { title: "Medley Russian Hits", artist: "DJ Mix", tags: "русский микс" }
].map((t, i) => ({
  id: 'C' + i,
  title: t.title,
  artist: t.artist,
  tags: t.tags || '',
  cover: '',
  duration: 200,
  preview: '',
  hot: true,
  local: true
}));
